image: maven:3.6.3-jdk-11

stages:
  - build
  - test
  - quality
  - deploy

build:
  #  tags:
  #    - build
  stage: build
  script:
    mvn clean compile

coverage:
  #  tags:
  #    - test
  stage: test
  script:
    mvn  clean -B -fae clover:setup test clover:aggregate clover:clover clover:check
  artifacts:
    paths:
      - ./target/site/clover
    expire_in: 2 weeks
    when: always

test:
  #  tags:
  #    - test
  stage: test
  script:
    mvn  test

sonar:
  #  tags:
  #    - quality
  stage: quality
  script:
    mvn clean verify sonar:sonar


#deploy:
#  tags:
#    - deploy
#  stage: deploy
#  script:
#    - ./mvnw package
#    - java -jar ./target/framadate-0.0.1-SNAPSHOT.jar