image: maven:3.6.3-jdk-11

stages:
  - build
  - test
  - quality
  - deploy

build:
  tags:
    - build
  stage: build
  script:
    - ./mvnw clean compile

coverage:
  tags:
    - test
  stage: test
  script:
    - ./mvnw  clean -B -fae clover:setup test clover:aggregate clover:clover clover:check
  artifacts:
    paths:
      - ./target/site/clover
    expire_in: 2 weeks
    when: always

test:
  tags:
    - test
  stage: test
  script:
    - ./mvnw  test

sonar:
  tags:
    - quality
  stage: quality
  script:
    ./mvnw clean verify sonar:sonar


deploy:
  tags:
    - deploy
  stage: deploy
  script:
    - ./mvnw package
    - java -jar ./target/framadate-0.0.1-SNAPSHOT.jar